### PR TITLE
revert to use the eval data

### PR DESCRIPTION
**Pull request by sw005320**

### CODE REVIEW

**Comment by sw005320** [comment]
I think it's working now. It would be great if you review it and merge it.

**Comment by boeddeker** [comment]
Thank you. Looks good for me.

**Comment by sw005320** [comment]
Thanks a lot!!!!
Could you also test the track 1 GSS part in https://github.com/chimechallenge/kaldi_chime6/pull/14?
We're almost there.

**Comment by boeddeker** [comment]
Sure. I will test it. At the moment I am testing if the performance for multiarray didn't change between my chime5 experiment and the implementation in kaldi for chime6.

**Comment by boeddeker** [comment]
I tested now the multi-array GSS in track 1 for the DEV dataset and got a WER of 62.85% with the baseline CHiME-5 ASR system (i.e. not with the new ASR). This is slightly better than the WER that I got with the CHiME-5 data. There the WER was 63.51%.
So at least on the DEV data, the enhancement works.

Now I will also test the EVAL data.

**Comment by sw005320** [comment]
Thanks.
I'm relieved to hear that.
I hope we'd not have some issues on the eval set, as well.

**Comment by boeddeker** [comment]
For the EVAL data the WER decreased. This is a bit strange, since the better synchronization should have no effect or slightly improve the WER.
%WER **60.71** [ 33472 / 55132, 2551 ins, 14623 del, 16298 sub ] .../**chime5**/.../eval/wer_8_0.5
%WER **61.60** [ 33964 / 55132, 2608 ins, 15187 del, 16169 sub ] .../**chime6**/.../eval/wer_8_0.5

**Pull request merged**
